---
- name: Install Health Check Script
  become: yes
  template:
      src: templates/docker-healthcheck.j2
      dest: /usr/local/bin/docker-healthcheck
      owner: root
      group: root
      mode: 0744
      backup: no
  when: docker_keep_alive_install

- name: Install Health Check Service
  become: yes
  template:
      src: templates/docker-healthcheck.service.j2
      dest: /etc/systemd/system/docker-healthcheck.service
      owner: root
      group: root
      mode: 744
      backup: no
  when: docker_keep_alive_install

- name: Install Health Check Timer
  become: yes
  template:
      src: templates/docker-healthcheck.timer.j2
      dest: /etc/systemd/system/docker-healthcheck.timer
      owner: root
      group: root
      mode: 744
      backup: no
  when: docker_keep_alive_install

- name: Restart Health Check Service
  become: yes
  systemd: state=restarted daemon_reload=yes name=docker-healthcheck
  when: docker_keep_alive_install

- name: Always Start Docker
  become: yes
  command: /bin/systemctl enable docker
  when: docker_keep_alive_install
